# docs https://github.com/marketplace/actions/create-release
# docs https://github.com/ncipollo/release-action

name: release

on: 
  push:
    tags:
      - '*'
    tags-ignore:
      - 'latest'

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    # electron build
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn
    - run: yarn build
    - run: yarn electron:build:linux
    - run: ls dist

    # publish version release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/plebbit*.AppImage,dist/plebbit-html*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: false
        body: "Progressive web app mirrors:\n- https://demo.plebbit.eth.limo\n- https://demo.plebbit.eth.link\n- https://cloudflare-ipfs.com/ipns/demo.plebbit.eth"
        allowUpdates: true

    # publish release 'latest'
    - uses: ncipollo/release-action@v1
      with:
        tag: latest
        artifacts: "dist/plebbit*.AppImage,dist/plebbit-html*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        # linux build finishes first, so use it to remove the previous release artifacts
        replacesArtifacts: true
        removeArtifacts: true
        body: "Progressive web app mirrors:\n- https://demo.plebbit.eth.limo\n- https://demo.plebbit.eth.link\n- https://cloudflare-ipfs.com/ipns/demo.plebbit.eth"
        allowUpdates: true

  mac:
    runs-on: macOS-latest
    permissions:
      contents: write
    steps:

    # electron build
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn
    - run: yarn build
    - run: yarn electron:build:mac
    - run: ls dist

    # publish version release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/plebbit*.dmg"
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: false
        body: "Progressive web app mirrors:\n- https://demo.plebbit.eth.limo\n- https://demo.plebbit.eth.link\n- https://cloudflare-ipfs.com/ipns/demo.plebbit.eth"
        allowUpdates: true

    # publish release 'latest'
    - uses: ncipollo/release-action@v1
      with:
        tag: latest
        artifacts: "dist/plebbit*.dmg"
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: false
        body: "Progressive web app mirrors:\n- https://demo.plebbit.eth.limo\n- https://demo.plebbit.eth.link\n- https://cloudflare-ipfs.com/ipns/demo.plebbit.eth"
        allowUpdates: true

  windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:

    # electron build
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn
    - run: yarn build
    - run: yarn electron:build:windows
    - run: dir dist

    # publish version release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/plebbit*.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: false
        body: "Progressive web app mirrors:\n- https://demo.plebbit.eth.limo\n- https://demo.plebbit.eth.link\n- https://cloudflare-ipfs.com/ipns/demo.plebbit.eth"
        allowUpdates: true

    # publish release 'latest'
    - uses: ncipollo/release-action@v1
      with:
        tag: latest
        artifacts: "dist/plebbit*.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: false
        body: "Progressive web app mirrors:\n- https://demo.plebbit.eth.limo\n- https://demo.plebbit.eth.link\n- https://cloudflare-ipfs.com/ipns/demo.plebbit.eth"
        allowUpdates: true
