# docs https://github.com/marketplace/actions/create-release
# docs https://github.com/ncipollo/release-action

name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    # electron build
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn
    - run: yarn build
    - run: yarn electron:build:linux
    - run: ls dist

    # publish version release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/plebbit*.AppImage,dist/plebbit-html*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: false
        body: "Progressive web app mirrors:\n- https://demo.plebbit.eth.limo\n- https://demo.plebbit.eth.link\n- https://cloudflare-ipfs.com/ipns/demo.plebbit.eth"
        allowUpdates: true

  mac:
    runs-on: macOS-latest
    permissions:
      contents: write
    steps:

    # electron build
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn
    - run: yarn build
    - run: yarn electron:build:mac
    - run: ls dist

    # publish version release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/plebbit*.dmg"
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: false
        body: "Progressive web app mirrors:\n- https://demo.plebbit.eth.limo\n- https://demo.plebbit.eth.link\n- https://cloudflare-ipfs.com/ipns/demo.plebbit.eth"
        allowUpdates: true

  windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:

    # electron build
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn
    - run: yarn build
    - run: yarn electron:build:windows
    - run: dir dist

    # publish version release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/plebbit*.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: false
        body: "Progressive web app mirrors:\n- https://demo.plebbit.eth.limo\n- https://demo.plebbit.eth.link\n- https://cloudflare-ipfs.com/ipns/demo.plebbit.eth"
        allowUpdates: true

  android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    # android build
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn
    - run: yarn build
    - run: npx cap update
    - run: npx cap copy
    - run: cd android && gradle bundle
    - run: cd android && ./gradlew assembleRelease
    - run: mkdir -p dist && mv android/app/build/outputs/apk/release/app-release-unsigned.apk dist/plebbit-$(node -e "console.log(require('./package.json').version)").apk
    - run: ls dist

    # publish version release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/plebbit*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: false
        body: "Progressive web app mirrors:\n- https://demo.plebbit.eth.limo\n- https://demo.plebbit.eth.link\n- https://cloudflare-ipfs.com/ipns/demo.plebbit.eth"
        allowUpdates: true
